DROP TABLE CONTENIR CASCADE CONSTRAINTS;
DROP TABLE TRONCONS CASCADE CONSTRAINTS;

DROP TABLE ETAPE CASCADE CONSTRAINTS;

DROP TABLE CATEGORIE CASCADE CONSTRAINTS;

DROP TABLE PARCOURS CASCADE CONSTRAINTS;
PURGE RECYCLEBIN;
COMMIT;